//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class project2Entities : DbContext
    {
        public project2Entities()
            : base("name=project2Entities")
        {
            // Inhibare: lazy loading si creare proxy dinamic.
            Configuration.LazyLoadingEnabled = false;
            Configuration.ProxyCreationEnabled = false;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<resource_attribute_values> resource_attribute_values { get; set; }
        public virtual DbSet<resource_attributes> resource_attributes { get; set; }
        public virtual DbSet<resource_eav> resource_eav { get; set; }
        public virtual DbSet<resource> resources { get; set; }
    }
}
