//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract(IsReference = true)]
    public partial class resource_attribute_values
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public resource_attribute_values()
        {
            this.resource_eav = new HashSet<resource_eav>();
        }

        [DataMember]
        public int Id { get; set; }
        [DataMember]
        public int attribute_id { get; set; }
        [DataMember]
        public string value { get; set; }
        [DataMember]
        public int resource_attributesId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [DataMember]
        public virtual ICollection<resource_eav> resource_eav { get; set; }
        [DataMember]
        public virtual resource_attributes resource_attributes { get; set; }
    }
}
